# Generated by Django 4.1 on 2023-04-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0004_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='prd_description',
            field=models.TextField(default=22.477777777777778),
            preserve_default=False,
        ),
    ]
