# Generated by Django 4.1 on 2023-04-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0006_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dairyapp.cart'),
        ),
    ]
